[project]
name = "github-actions-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.122.0",
    "uvicorn[standar,standard]>=0.38.0",
]
