name: test download

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  test_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: create files
        run: python create-files.py
      - uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            file*
            tfile*
            gfile*

  test_download:
    runs-on: ubuntu-latest
    needs: test_upload
    steps: 
      - uses: actions/checkout@v3   
      - uses:  actions/download-artifact@v5
        with:
          name: files
          path: files
      - name: display file names
        run: ls -alrt
      - uses: actions/setup-python@v3
      - name: display contents
        run: python read_files.py