name: matrix

on:
  push:
  workflow_dispatch:
  worflow_call:

jobs:
  job1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: [ "file1" , "file2", "file3"]
        colors: ["red", "green", "blue"]
        include:
          - files: "file4"
          - code: [ "#45#" , "#3AB#"]
    
    steps:
      - name: create files
        run: echo "${{ matrix.files }}-${{ matrix.colors }}-${{ matrix.code }}" > ${{ matrix.files }}-${{ matrix.colors }}.txt
      - name: list dir
        run: ls -alrt
      - name: show contents
        run: cat ${{ matrix.files }}-${{ matrix.colors }}.txt