name: test upload

on:
  push:
    branches:
      - main

jobs:
  test_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: create files
        run: python create-files.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: files
          path: |
            file*